### ISSUE TITLE
建议增加调整打开后默认窗口宽度

### ISSUE THREAD

**Issue by AEliu** [estepona/wx-read-desktop#25]
```css
@media(max-width: 700px) {
    .wr_horizontalReader .readerChapterContent {
        width:100%;
        max-width: 100%;
        height: 100%;
        margin: 0;
        border-radius: 0
    }
```
网页有这么一段css代码，700 px 宽度时，各种设置按钮、头像啥的都隐藏了，如下图，能否增加一个调整参数，在每次打开程序后可以固定宽度？
感谢。
![image](https://github.com/user-attachments/assets/e8e81b60-64bf-4a8e-8e5e-7b7461c7a171)
